FONT_SIZES = {
    "x-small": 0.7,
    "smaller": 0.8,
    "small": 0.9,
    "normal": 1,
    "large": 1.1,
    "larger": 1.2,
    "x-large": 1.3
}

LOCALE_MAP = {
    "af": "Afrikaans",
    "ar-dz": "Arabisch (Algerien)",
    "ar-kw": "Arabisch (Kuwait)",
    "ar-ly": "Arabisch (Libyen)",
    "ar-ma": "Arabisch (Marokko)",
    "ar-sa": "Arabisch (Saudi-Arabien)",
    "ar-tn": "Arabisch (Tunesien)",
    "ar": "Arabisch",
    "az": "Aserbaidschanisch",
    "bg": "Bulgarisch",
    "bn": "Bengalisch",
    "bs": "Bosnisch",
    "ca": "Katalanisch",
    "cs": "Tschechisch",
    "cy": "Walisisch",
    "da": "Dänisch",
    "de-at": "Deutsch (Österreich)",
    "de": "Deutsch",
    "el": "Griechisch",
    "en": "Englisch",
    "en-au": "Englisch (Australien)",
    "en-gb": "Englisch (Vereinigtes Königreich)",
    "en-nz": "Englisch (Neuseeland)",
    "eo": "Esperanto",
    "es-us": "Spanisch (USA)",
    "es": "Spanisch",
    "et": "Estnisch",
    "eu": "Baskisch",
    "fa": "Persisch",
    "fi": "Finnisch",
    "fr-ca": "Französisch (Kanada)",
    "fr-ch": "Französisch (Schweiz)",
    "fr": "Französisch",
    "gl": "Galicisch",
    "he": "Hebräisch",
    "hi": "Hindi",
    "hr": "Kroatisch",
    "hu": "Ungarisch",
    "hy-am": "Armenisch",
    "id": "Indonesisch",
    "is": "Isländisch",
    "it": "Italienisch",
    "ja": "Japanisch",
    "ka": "Georgisch",
    "kk": "Kasachisch",
    "km": "Khmer",
    "ko": "Koreanisch",
    "ku": "Kurdisch",
    "lb": "Luxemburgisch",
    "lt": "Litauisch",
    "lv": "Lettisch",
    "mk": "Mazedonisch",
    "ms": "Malaiisch",
    "nb": "Norwegisch (Bokmål)",
    "ne": "Nepalesisch",
    "nl": "Niederländisch",
    "nn": "Norwegisch (Nynorsk)",
    "pl": "Polnisch",
    "pt-br": "Portugiesisch (Brasilien)",
    "pt": "Portugiesisch",
    "ro": "Rumänisch",
    "ru": "Russisch",
    "si-lk": "Singhalesisch (Sri Lanka)",
    "sk": "Slowakisch",
    "sl": "Slowenisch",
    "sm": "Samoanisch",
    "sq": "Albanisch",
    "sr-cyrl": "Serbisch (Kyrillisch)",
    "sr": "Serbisch (Lateinisch)",
    "sv": "Schwedisch",
    "ta-in": "Tamil (Indien)",
    "th": "Thailändisch",
    "tr": "Türkisch",
    "ug": "Uigurisch",
    "uk": "Ukrainisch",
    "uz-cy": "Usbekisch (Kyrillisch)",
    "uz": "Usbekisch (Lateinisch)",
    "vi": "Vietnamesisch",
    "zh-cn": "Chinesisch (vereinfacht)",
    "zh-tw": "Chinesisch (traditionell)"
}